src/Entity/Collaborateur.php
<?php

namespace App\Entity;

use App\Repository\CollaborateurRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CollaborateurRepository::class)]
class Collaborateur
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(length: 255)]
    private ?string $adress_mail = null;

    #[ORM\ManyToMany(targetEntity: Projet::class, mappedBy: 'Collaborateurs')]
    private Collection $projets;

    public function __construct()
    {
        $this->projets = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getAdressMail(): ?string
    {
        return $this->adress_mail;
    }

    public function setAdressMail(string $adress_mail): static
    {
        $this->adress_mail = $adress_mail;

        return $this;
    }

    /**
     * @return Collection<int, Projet>
     */
    public function getProjets(): Collection
    {
        return $this->projets;
    }

    public function addProjet(Projet $projet): static
    {
        if (!$this->projets->contains($projet)) {
            $this->projets->add($projet);
            $projet->addCollaborateur($this);
        }

        return $this;
    }

    public function removeProjet(Projet $projet): static
    {
        if ($this->projets->removeElement($projet)) {
            $projet->removeCollaborateur($this);
        }

        return $this;
    }

    public function getNomPrenom(): string
{
    return $this->nom . ' ' . $this->prenom;
}

// Dans votre entité Projet




}

src/Controller/CollaborateurController.php
<?php

namespace App\Controller;

use App\Entity\Collaborateur;
use App\Form\AddCollaborateurType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;



class CollaborateurController extends AbstractController
{
    
   
    #[Route('/collaborateur', name: 'app_collaborateur')]
    public function index(ManagerRegistry $doctrine, Request $request, PaginatorInterface $paginator): Response
    {
        $em = $doctrine->getManager();
        $query = $em->getRepository(Collaborateur::class)->createQueryBuilder('p');

        $pagination = $paginator->paginate(
            $query->getQuery(),
            $request->query->getInt('page', 1), // Récupère le numéro de page de la requête, par défaut 1
            10 // Nombre d'éléments par page
        );

        return $this->render('collaborateur/index.html.twig', [
            'pagination' => $pagination,
        ]);
    }

    #[Route('/add/{id?0}', name: 'collaborateur.add')]
    public function addCollaborateur(
        Collaborateur $collaborateur = null,
        ManagerRegistry $doctrine,
        Request $request,
        int $id = 0
    ): Response {
        $entityManager = $doctrine->getManager();
        $new = false;
    
        // Si $collaborateur est null, créez une nouvelle instance de Collaborateur
        if (!$collaborateur) {
            $new = true;
    
            // Si $id est spécifié dans l'URL, récupérez le collaborateur correspondant
            if ($id) {
                $collaborateur = $entityManager->getRepository(Collaborateur::class)->find($id);
    
                // Si le collaborateur n'est pas trouvé, redirigez vers la page d'ajout avec un message d'erreur
                if (!$collaborateur) {
                    $this->addFlash('error', 'Collaborateur non trouvé');
                    return $this->redirectToRoute('collaborateur.add');
                }
            } else {
                $collaborateur = new Collaborateur();
            }
        }
    
        // Création du formulaire
        $form = $this->createForm(AddCollaborateurType::class, $collaborateur);
    
        // Traitement de la requête
        $form->handleRequest($request);
    
        // Vérifie si le formulaire a été soumis et est valide
        if ($form->isSubmitted() && $form->isValid()) {
            // Gestion de l'entité dans la base de données
            $entityManager->persist($collaborateur);
            $entityManager->flush();
    
            // Ajout d'un message de succès
            $message = $new ? "Le collaborateur a été ajouté avec succès." : "Le collaborateur a été mis à jour avec succès.";
            $this->addFlash('success', $message);
    
            // Redirection vers la liste des collaborateurs
            return $this->redirectToRoute('app_collaborateur');
        }
    
        // Affichage du formulaire avec les erreurs
        return $this->render('collaborateur/addCollaborateur.html.twig', [
            'form' => $form->createView(),
        ]);
    }


    #[Route('/collaborateur/{id}/delete', name: 'collaborateur.delete')]
    public function delete(int $id, ManagerRegistry $doctrine): RedirectResponse
    {
        $entityManager = $doctrine->getManager();
    
        // Récupérer le collaborateur
        $collaborateur = $entityManager->getRepository(Collaborateur::class)->find($id);
    
        if (!$collaborateur) {
            throw new NotFoundHttpException('Collaborateur non trouvé.');
        }
    
        // Supprimer les références dans les Projets associés
        foreach ($collaborateur->getProjets() as $projet) {
            $entityManager->remove($projet); 
        }
    
        // Supprimer le collaborateur
        $entityManager->remove($collaborateur);
        $entityManager->flush();
    
        $this->addFlash('success', 'Le Collaborateur a été supprimé avec succès.');
    
        return $this->redirectToRoute('app_collaborateur');
    }
    

}

templates/collaborateur/addCollaborateur.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container mt-4">
        <div class="text-center">
            <h1>Formulaire d'ajout d'un Collaborateur</h1>
        </div>

        {{ form_start(form, {'attr': {'class': 'row g-3 mx-auto'}}) }}
        <div class="col-md-6">
            {{ form_row(form.nom, {'attr': {'class': 'form-control', 'placeholder': 'Nom du collaborateur'}}) }}
        </div>
        <div class="col-md-6">
            {{ form_row(form.prenom, {'attr': {'class': 'form-control', 'placeholder': 'Prénom du collaborateur'}}) }}
        </div>
        <div class="col-md-6">
            {{ form_row(form.adress_mail, {'attr': {'class': 'form-control', 'placeholder': 'Adresse e-mail'}}) }}
        </div>
        {# <div class="col-md-6">
            {{ form_row(form.projets, {'attr': {'class': 'form-control', 'placeholder': 'Projets associés'}}) }}
        </div> #}

        {{ form_rest(form) }}

        {{ form_end(form) }}
    </div>
{% endblock %}

templates/collaborateur/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des Projets{% endblock %}

{% block body %}
<div class="container mt-4">
    <h2>Liste des Collaborateurs</h2>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Nom</th>
                <th scope="col">Prénom</th>
                <th scope="col">Adresse mail</th>
                {# <th scope="col">Statut</th> #}
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for collaborateur in pagination %}
                <tr>
                    <td>{{ collaborateur.nom }}</td>
                    <td>{{ collaborateur.prenom }}</td>
                    <td>{{ collaborateur.adressMail}}</td> 
                    <td>
                       
                        {% if is_granted('ROLE_ADMIN') %}
                            <a href="{{ path('collaborateur.delete', {id: collaborateur.id}) }}" class="btn btn-danger btn-sm">
                                <i class="fas fa-user-times"></i> 
                            </a>
                            <a href="{{ path('collaborateur.add', {id: collaborateur.id}) }}" class="btn btn-warning btn-sm">
                                <i class="fas fa-user-edit"></i> 
                            </a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

     {% if is_granted('ROLE_ADMIN') %}
<div class = "mb-4">
			<a href="{{ path('collaborateur.add') }}" class="btn btn-secondary">Ajout Collaborateur</a>
			</div>    {% endif %}
</div>

 <div class="pagination">
        {{ knp_pagination_render(pagination) }}
    </div>
{% endblock %}